/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import ContentBlock from './ContentBlock.jsx';

const components = new Map();
components.set('React-ContentBlock', ContentBlock);

export default function componentFactory(componentName) {
  return components.get(componentName);
};
