name: Publish @exdst-sitecore-content-sdk/astro to NPM
on:
  release:
    types: [created]
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: node --version && npm --version
      - run: npm ci
        working-directory: ./astro-content-sdk/packages/astro-content-sdk
      - run: npm run build --if-present
        working-directory: ./astro-content-sdk/packages/astro-content-sdk
      - run: npm publish
        working-directory: ./astro-content-sdk/packages/astro-content-sdk
