name: Publish @exdst-sitecore-content-sdk/create-astro to NPM
on:
  release:
    types: [created]
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm i
        working-directory: ./astro-content-sdk/packages/create-astro-content-sdk-app
      - run: npm run build --if-present
        working-directory: ./astro-content-sdk/packages/create-astro-content-sdk-app
      - run: npm publish
        working-directory: ./astro-content-sdk/packages/create-astro-content-sdk-app
