name: Publish astro-sitecore-jss to NPM
on:
  release:
    types: [created]
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: ./astro-sitecore-jss/packages/astro-sitecore-jss
      - run: npm run build --if-present
        working-directory: ./astro-sitecore-jss/packages/astro-sitecore-jss
      - run: npm publish
        working-directory: ./astro-sitecore-jss/packages/astro-sitecore-jss
